import { JetBrains_Mono as JetBrainsMonoFont } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import PageTransition from "../components/PageTransition";
import Header from "@/components/Header";
import StairTransition from "@/components/StairTransition";

// Google Font
const jetbrainsMono = JetBrainsMonoFont({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrainsMono",
});

// Local Font
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jetbrainsMono.variable} ${geistMono.variable}`}>
        <Header />
        <StairTransition />
        <PageTransition>{children}</PageTransition>
        <StairTransition />
      </body>
    </html>
  );
}